/* Main function of the C program. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "FreeRTOS_CLI.h"

/* Dimensions the buffer into which input characters are placed. */
#define cmdMAX_INPUT_SIZE	60

/* Dimensions the buffer into which string outputs can be placed. */
#define cmdMAX_OUTPUT_SIZE	1024

/* Dimensions the buffer passed to the recvfrom() call. */
#define cmdSOCKET_INPUT_BUFFER_SIZE 60


int main()
{
    static signed char cInputString[ cmdMAX_INPUT_SIZE ], cOutputString[ cmdMAX_OUTPUT_SIZE ], cLocalBuffer[ cmdSOCKET_INPUT_BUFFER_SIZE ];
    signed char cInChar, cInputIndex = 0;
    BaseType_t xMoreDataToFollow;
    puts("Hello World!");
    
    while(1)
    {

    	/* The next character in the input buffer. */
    	cInChar = getchar();
    
    	/* Newline characters are taken as the end of the command
    	string. */
    	if( cInChar == '\n' )
    	{
    		/* Process the input string received prior to the
    		newline. */
    		do
    		{
    			/* Pass the string to FreeRTOS+CLI. */
    			xMoreDataToFollow = FreeRTOS_CLIProcessCommand( cInputString, cOutputString, cmdMAX_OUTPUT_SIZE );
    
    			/* Send the output generated by the command's
    			implementation. */
    			 printf("%s", cOutputString);
    
    		} while( xMoreDataToFollow != pdFALSE ); /* Until the command does not generate any more output. */
    
    		/* All the strings generated by the command processing
    		have been sent.  Clear the input string ready to receive
    		the next command. */
    		cInputIndex = 0;
    		memset( cInputString, 0x00, cmdMAX_INPUT_SIZE );
    
    		/* Transmit a spacer, just to make the command console
    		easier to read. */
    		 printf("\r\n"); 
    	}
    	else
    	{
    		if( cInChar == '\r' )
    		{
    			/* Ignore the character.  Newlines are used to
    			detect the end of the input string. */
    		}
    		else if( cInChar == '\b' )
    		{
    			/* Backspace was pressed.  Erase the last character
    			in the string - if any. */
    			if( cInputIndex > 0 )
    			{
    				cInputIndex--;
    				cInputString[ cInputIndex ] = '\0';
    			}
    		}
    		else
    		{
    			/* A character was entered.  Add it to the string
    			entered so far.  When a \n is entered the complete
    			string will be passed to the command interpreter. */
    			if( cInputIndex < cmdMAX_INPUT_SIZE )
    			{
    				cInputString[ cInputIndex ] = cInChar;
    				cInputIndex++;
    			}
    		}
    	}
        
    }
    
    
    
    
    return EXIT_SUCCESS;
}

